### ISSUE TITLE
[question] Audit de perf sur pix.fr

### ISSUE THREAD

**Issue by xav-car** [SocialGouv/dashlord#18]
Bonjour, 

Chez Pix nous nous sommes rendu compte d'une inconsistence entre les résultats présent dans le tableau et la réalité des développement.

L'outil que nous avons mis en place en amont de nos applications utilise des règles d'autorisations. Celui-ci semble bloquer votre instance de google ligthouse car il ne reconnait pas votre ISP.

Si nous voulons avoir des données réels quand aux performances de l'application. Il nous faudrait votre ISP afin que l'on puisse l'ajouter dans notre whitelisting applicatif.

Je serais ravi de pouvoir échanger sur ce sujet.

Merci,
Bonne journée

**Comment by revolunet** [comment]
Bonjour @xav-car , les scans sont actuellement faits par des github runners, les IPs sont celles d'Azure, c'est large :/ 
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#ip-addresses

sur la métrique "performance" en fait on a changé la manière dont elle est calculée, en se basant maintenant sur [ce code naïf](https://github.com/SocialGouv/dashlord-report-action/blob/master/www/src/lib/lighthouse/getPerformanceScore.ts) dont on peut discuter :)  dans votre cas vous êtes pénalisés a cause du nombre de requêtes (59) et du "first paint" à 2 secondes.

Le calcul actuel est arbitraire, il faut qu'on l'affine avec la communauté :)

j'ai fait ce changement pour deux raisons : 
  - Le scan lighthouse est fait sur github actions et effectué depuis les Etats-unis , donc pas hyper précis pour nous
  - On ne peut pas se fier au résultat d'un seul scan il faudrait fait une moyenne sur trois runs pour que ce soit plus réaliste. c'est faisable si quelqu'un a un peu de temps pour faire une PR [par ici](https://github.com/SocialGouv/dashlord-save-action/blob/master/action.yml#L64)

Si tu es sur le slack beta je t'invite à rejoindre le channel #incubateur-dashlord pour creuser le sujet :)
