### ISSUE TITLE
Bug (push colision on github)

### ISSUE THREAD

**Issue by jdauphant** [SocialGouv/dashlord#28]
Apparently 2 jobs have finished, generate commit and push it in same time : (not 100% sure of my conclusion)
![image](https://user-images.githubusercontent.com/1238254/126539629-c690d0c5-0cc5-4a45-ac8d-260b8ea4d9b4.png)

**Comment by revolunet** [comment]
peut-être résolu avec cette astuce : https://github.com/SocialGouv/dashlord-fabrique/blob/main/.github/workflows/scans.yml#L233
