### ISSUE TITLE
Nouvelle URL à scanner

### ISSUE THREAD

**Issue by Jeremieval** [SocialGouv/dashlord#30]
https://inclusion.beta.gouv.fr/

**Comment by revolunet** [comment]
fixed : https://github.com/betagouv/dashlord/commit/cbe7c3e1f8836c8941473ce8b5c2445428e30b94

**Comment by revolunet** [comment]
dispo : https://dashlord.incubateur.net/#/url/https://inclusion.beta.gouv.fr/
