### ISSUE TITLE
Ajout de nouvelles URL

### ISSUE THREAD

**Issue by Jeremieval** [SocialGouv/dashlord#33]
1 URL à ajouter SVP : 
https://mes-aides.1jeune1solution.beta.gouv.fr/

Merci beaucoup

Jérémie

**Comment by revolunet** [comment]
disponible ici : https://socialgouv.github.io/dnum-dashboard/#/url/https%3A%2F%2Fmes-aides.1jeune1solution.beta.gouv.fr
