### ISSUE TITLE
Demande d'inscription des url de eva

### ISSUE THREAD

**Issue by etienneCharignon** [SocialGouv/dashlord#34]
Serait-il possible d'inscrire les URL opérationnelle d'eva : 

    https://app.eva.beta.gouv.fr/
Le dépôt de source correspondant : https://github.com/betagouv/eva

Et peut-être aussi le back office si c'est utile :

    https://api.app.eva.beta.gouv.fr
Le dépôt de source correspondant : https://github.com/betagouv/eva-serveur

**Comment by revolunet** [comment]
C'est ajouté, ca devrait etre en ligne sur https://dashlord.incubateur.net/ d'ici demain soir

Bonne journée
