### ISSUE TITLE
[feature] add current tab on url to share it easely

### ISSUE THREAD

**Issue by jdauphant** [SocialGouv/dashlord#41]
I want to share the open tab "Informations" for example but the link with always open the "Bonnes pratiques" tab by default.
![image](https://user-images.githubusercontent.com/1238254/142690990-e1551a51-f251-41f7-bc5e-e52f297feda2.png)

**Comment by revolunet** [comment]
Yes, tabs are not routed and have also broken badge links from the dashboard 😿 

I have a Next.js (static) migration in mind, which could solve this and also reduce initial payload sizes

**Comment by revolunet** [comment]
ca marche a moitié avec la "nouvelle version" : si on clique sur un des indicateurs depuis le dashlord, on a un lien direct vers l'item en question.

par contre le changement d'onglet ne met pas encore à jour l'URL, souci d'integration avec react-dsfr

**Comment by revolunet** [comment]
ex: https://socialgouv.github.io/dashlord-fabrique/url/enfants-du-spectacle-fabrique-social-gouv-fr/best-practices/#stats
