### ISSUE TITLE
[report] asset URLs are absolute not relative (or missing base-url)

### ISSUE THREAD

**Issue by arthurzenika** [SocialGouv/dashlord#58]
https://socialgouv.github.io/dashlord/ has it's CSS/js broken since it's trying to get the assets from /_next/ not <PROJECT>/_next/ (or ./_next/)

For example https://socialgouv.github.io/_next/static/css/017eacd8855d90bf.css (404) should be https://socialgouv.github.io/dashlord/_next/static/css/017eacd8855d90bf.css (200)

![Screenshot from 2022-03-10 16-04-39](https://user-images.githubusercontent.com/445200/157690584-e6480a89-f9f7-48b1-8f23-74bf748af2f4.png)

This is probably a but in the `report` action, but not sure if this issue should be filed on https://github.com/SocialGouv/dashlord-actions instead

**Comment by revolunet** [comment]
en effet désolé pour la regression, vous devez ajouter le "base path" lors du lancement de l'action comme ici : 

https://github.com/SocialGouv/dashlord-fabrique/blob/main/.github/workflows/report.yml#L34

**Comment by revolunet** [comment]
bien vu merci.

ceci devrait corriger le souci : https://github.com/SocialGouv/dashlord/commit/a1e3b05502200195d014ed726def3e6cb0376a97

**Comment by arthurzenika** [comment]
Je rajoute cela à mon dashlord. Est-ce que cela risque de casser l'usage "Template" du coup ? Faut-il ajouter une étape dans le README pour que l'action report soit modifiée avec le nom du projet ?
