### ISSUE TITLE
Clarifier la license de Dashlord

### ISSUE THREAD

**Issue by landure** [SocialGouv/dashlord#76]
Dashlord viens d'obtenir une visibilité supplémentaire avec son entrée au SILL.

le fichier LICENSE de Dashlord utilise la licence Apache 2 et le logiciel est publié dans un dépôt GitHub open-source.
Cependant, le README affiche ce message :

> ⚠️ DashLord utilise le [Système de Design de l'État](https://www.systeme-de-design.gouv.fr/) et s'adresse donc uniquement aux développeurs et aux concepteurs, qu'ils soient agents publics ou prestataires pour des sites Internet de l'État. cf [conditions d'utilisation](https://www.systeme-de-design.gouv.fr/utilisation-et-organisation/perimetre-d-application)

Pourriez-vous clarifier cela ? Est-ce que l'utilisation de Dashlord est complètement interdit pour une entreprise privée non reliée à l'état français ? Si ce n'est pas le cas, dans quelles conditions est autorisée l'utilisation de Dashlord ?

It would also be interesting to translate the documentation in english if private use of Dashlord is allowed, and if private use isn't allowed, the warning should be given both in french and english.

Thank you for your work. I really hope private use is allowed :)

**Comment by revolunet** [comment]
Bonjour, merci pour votre message.

Actuellement le thème graphique utilisé par le frontend DashLord est basé sur le design système de l'état, dont l'usage est réservé "uniquement aux développeurs et aux concepteurs, qu'ils soient agents publics ou prestataires pour des sites Internet de l'État".

Sur les CGU du DSFR : 

<img width="818" alt="Capture d’écran 2023-09-05 à 11 23 42" src="https://github.com/SocialGouv/dashlord/assets/124937/f05a6f52-d2cc-46e7-b49f-10b91a1aa444">

Donc dans l'état actuel je pense que qu'il n'est pas possible pour le privé d'utiliser ce thème graphique, donc DashLord.

Il est prévu une petite refonte du frontend, on prendra en compte le fait de pouvoir "switcher" de thème, on peut en parler si vous souhaitez contribuer.

Cordialement

**Comment by edelagnier** [comment]
Bonjour, 

Je serai justement intéressée pour contribuer à la possibilité de switcher le théme pour ouvrir le projet aux sites hors de l'État.  Seriez vous toujours partant pour en discuter ?

Bonne journée

**Comment by revolunet** [comment]
Bonjour, avec plaisir pour en discuter; vous ne seriez pas à [NEC](https://numerique-en-communs.fr/) cette semaine par hasard ?

**Comment by edelagnier** [comment]
Ah pratique ! oui j'y serai. Je vous contacte par mail

**Comment by revolunet** [comment]
@landure Bonjour, @edelagnier a fait une amélioration qui permet maintenant d'utiliser DashLord sans utiliser la marque de l'état.

il suffit de positionner `marianne: false` dans le `dashlord.yaml`

**Comment by revolunet** [comment]
And yes, we'd be happy to have an english documentation as well :)

**Comment by landure** [comment]
Merci !
