### ISSUE TITLE
Blocage du Workflow Dashlord report à cause de TypeError

### ISSUE THREAD

**Issue by Khaled-Abdalbaki** [SocialGouv/dashlord#91]
Le workflow Dashlord report est bloqué en raison d'une erreur"TypeError: h.includes is not a function" . Cette erreur empêche l'exécution correcte du workflow, nécessitant une investigation et une correction pour rétablir la fonctionnalité . Cette même erreur est également visible dans le dépôt officiel de Dashlord sous Actions -> Dashlord report. Comment puis-je résoudre ce problème pour générer correctement le rapport ?

**Comment by revolunet** [comment]
Bonjour, désolé c'est bien une regression; C'est corrigé dans la dernière release, si vous relancez le workflow de report cela devrait fonctionner.

Cordialement
